Fixes (#6328)
* Round of security fixes

* second set of changes

* Fixes

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -2,6 +2,11 @@
 
 source bin/config.env
 
+if [ "$RAILS_ENV" = "production" ] && [ -z "$URL_HOST" ] && [ "$BYPASS_HOST" != "true" ]; then
+  echo "ERROR: URL_HOST must be set to the hostname Greenlight is served from."
+  exit 1
+fi
+
 echo "Greenlight-v3 starting on port: $PORT"
 
 echo "Postgres host: $PGHOST"
